### ISSUE TITLE
Not Available on PyPi

### ISSUE THREAD

**Issue by shawneeunion** [CDCgov/pynssp#3]
Hi,

I'm unable to install the pynssp package by referencing just the package name on PyPi. When searching the PyPi website for the package it does not show up either. I'm able to install other packages and wondering if the PyPi directory is currently available.

**Comment by rosericazondekon** [comment]
Hi @shawneeunion 
The package is not yet available on PyPi since we have not released its first version yet. Please, install the development version by running the following from your terminal or command prompt (assuming that you have `pip` installed):

```sh
pip install git+https://github.com/CDCgov/pynssp.git
```

Hope this helps. Don't hesitate to let me know should you need further assistance.
Thanks
